DROP TABLE IF EXISTS nyc_council_raw_data;

CREATE TABLE IF NOT EXISTS nyc_council_raw_data(
    MatterID                 INTEGER,
    MatterGUID               TEXT PRIMARY KEY,
    MatterLastModifiedUtc    TEXT,
    MatterRowVersion         TEXT,
    MatterFile               TEXT,
    MatterName               TEXT,
    MatterTitle              TEXT,
    MatterTypeID             INTEGER,
    MatterTypeName           TEXT,
    MatterStatusID           INTEGER,
    MatterStatusName         TEXT,
    MatterBodyID             INTEGER,
    MatterBodyName           TEXT,
    MatterIntroDate          TEXT,
    MatterAgendaDate         TEXT,
    MatterPassedDate         TEXT,
    MatterEnactmentDate      TEXT,
    MatterEnactmentNumber    TEXT,
    MatterRequester          TEXT,
    MatterNotes              TEXT,
    MatterVersion            TEXT,
    MatterText1              TEXT,
    MatterText2              TEXT,
    MatterText3              TEXT,
    MatterText4              TEXT,
    MatterText5              TEXT,
    MatterDate1              TEXT,
    MatterDate2              TEXT,
    MatterEXText1            TEXT,
    MatterEXText2            TEXT,
    MatterEXText3            TEXT,
    MatterEXText4            TEXT,
    MatterEXText5            TEXT,
    MatterEXText6            TEXT,
    MatterEXText7            TEXT,
    MatterEXText8            TEXT,
    MatterEXText9            TEXT,
    MatterEXText10           TEXT,
    MatterEXText11           TEXT,
    MatterEXDate1            TEXT,
    MatterEXDate2            TEXT,
    MatterEXDate3            TEXT,
    MatterEXDate4            TEXT,
    MatterEXDate5            TEXT,
    MatterEXDate6            TEXT,
    MatterEXDate7            TEXT,
    MatterEXDate8            TEXT,
    MatterEXDate9            TEXT,
    MatterEXDate10           TEXT,
    MatterAgiloftID          INTEGER,
    MatterReference          TEXT,
    MatterRestrictViewViaWeb BOOLEAN
);

DROP TABLE IF EXISTS nyc_council_raw_data_diff;

CREATE TABLE IF NOT EXISTS nyc_council_raw_data_diff(
    updated_at_timestamp     TIMESTAMP,
    MatterID                 INTEGER,
    MatterGUID               TEXT,
    MatterLastModifiedUtc    TEXT,
    MatterRowVersion         TEXT,
    MatterFile               TEXT,
    MatterName               TEXT,
    MatterTitle              TEXT,
    MatterTypeID             INTEGER,
    MatterTypeName           TEXT,
    MatterStatusID           INTEGER,
    MatterStatusName         TEXT,
    MatterBodyID             INTEGER,
    MatterBodyName           TEXT,
    MatterIntroDate          TEXT,
    MatterAgendaDate         TEXT,
    MatterPassedDate         TEXT,
    MatterEnactmentDate      TEXT,
    MatterEnactmentNumber    TEXT,
    MatterRequester          TEXT,
    MatterNotes              TEXT,
    MatterVersion            TEXT,
    MatterText1              TEXT,
    MatterText2              TEXT,
    MatterText3              TEXT,
    MatterText4              TEXT,
    MatterText5              TEXT,
    MatterDate1              TEXT,
    MatterDate2              TEXT,
    MatterEXText1            TEXT,
    MatterEXText2            TEXT,
    MatterEXText3            TEXT,
    MatterEXText4            TEXT,
    MatterEXText5            TEXT,
    MatterEXText6            TEXT,
    MatterEXText7            TEXT,
    MatterEXText8            TEXT,
    MatterEXText9            TEXT,
    MatterEXText10           TEXT,
    MatterEXText11           TEXT,
    MatterEXDate1            TEXT,
    MatterEXDate2            TEXT,
    MatterEXDate3            TEXT,
    MatterEXDate4            TEXT,
    MatterEXDate5            TEXT,
    MatterEXDate6            TEXT,
    MatterEXDate7            TEXT,
    MatterEXDate8            TEXT,
    MatterEXDate9            TEXT,
    MatterEXDate10           TEXT,
    MatterAgiloftID          INTEGER,
    MatterReference          TEXT,
    MatterRestrictViewViaWeb BOOLEAN
);

CREATE OR REPLACE FUNCTION store_row_diff_on_change()
RETURNS trigger
AS $$ begin
    if (NEW IS DISTINCT FROM OLD) then
        INSERT INTO nyc_council_raw_data_diff VALUES(
            NOW(),
            NEW.MatterID,
            NEW.MatterGUID,
            NEW.MatterLastModifiedUtc,
            NEW.MatterRowVersion,
            NEW.MatterFile,
            NEW.MatterName,
            NEW.MatterTitle,
            NEW.MatterTypeID,
            NEW.MatterTypeName,
            NEW.MatterStatusID,
            NEW.MatterStatusName,
            NEW.MatterBodyID,
            NEW.MatterBodyName,
            NEW.MatterIntroDate,
            NEW.MatterAgendaDate,
            NEW.MatterPassedDate,
            NEW.MatterEnactmentDate,
            NEW.MatterEnactmentNumber,
            NEW.MatterRequester,
            NEW.MatterNotes,
            NEW.MatterVersion,
            NEW.MatterText1,
            NEW.MatterText2,
            NEW.MatterText3,
            NEW.MatterText4,
            NEW.MatterText5,
            NEW.MatterDate1,
            NEW.MatterDate2,
            NEW.MatterEXText1,
            NEW.MatterEXText2,
            NEW.MatterEXText3,
            NEW.MatterEXText4,
            NEW.MatterEXText5,
            NEW.MatterEXText6,
            NEW.MatterEXText7,
            NEW.MatterEXText8,
            NEW.MatterEXText9,
            NEW.MatterEXText10,
            NEW.MatterEXText11,
            NEW.MatterEXDate1,
            NEW.MatterEXDate2,
            NEW.MatterEXDate3,
            NEW.MatterEXDate4,
            NEW.MatterEXDate5,
            NEW.MatterEXDate6,
            NEW.MatterEXDate7,
            NEW.MatterEXDate8,
            NEW.MatterEXDate9,
            NEW.MatterEXDate10,
            NEW.MatterAgiloftID,
            NEW.MatterReference,
            NEW.MatterRestrictViewViaWeb
        );
    end if;
    RETURN NULL;
end;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS store_row_diff_on_change_trigger ON nyc_council_raw_data;
DROP TRIGGER IF EXISTS store_row_diff_on_change_trigger_on_create ON nyc_council_raw_data;

CREATE TRIGGER store_row_diff_on_change_trigger
    BEFORE UPDATE ON nyc_council_raw_data FOR EACH ROW
    EXECUTE FUNCTION store_row_diff_on_change();

CREATE TRIGGER store_row_diff_on_change_trigger_on_create
    BEFORE INSERT ON nyc_council_raw_data FOR EACH ROW
    EXECUTE FUNCTION store_row_diff_on_change();

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO politicker;
